sudo: false

language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: beta-xcode6.2

before_install:
  - brew update

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - brew tap dflemstr/v8
  - brew install --verbose --build-bottle dflemstr/v8/v8
  - brew bottle dflemstr/v8/v8

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "*.bottle.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: dflemstr/homebrew-v8
    tags: true
  overwrite: true
