sudo: false

language: cpp
os: osx

matrix:
  include:
    - osx_image: xcode8
    - osx_image: xcode7.1
    - osx_image: beta-xcode6.2

branches:
  only:
    - master

before_install:
  - brew update

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - brew install --verbose --build-bottle v8.rb
  - brew bottle v8

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "*.bottle.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: dflemstr/homebrew-v8
  overwrite: true
